FROM node:22-alpine

# 必要なツールをインストール
RUN apk update && apk add --no-cache \
    git \
    curl \
    ca-certificates \
    openssh

WORKDIR /usr/src/app

# スクリプトをコピーして実行権限を付与
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

CMD ["/usr/local/bin/start.sh"]